sudo: true

matrix:
    include:
        - os: linux
          language: node_js
          node_js:
              - 12

cache:
    directories:
        - '$HOME/.npm'

before_install:
    - npm install -g xvfb-maybe

# Remove this block if you are not using Greenkeeper
# On Travis, the default is to use `npm ci` which is better
install:
    - npm install

script:
    - npm run cs -- -l
    - xvfb-maybe npm run test
